# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0e056e05ddc202e37d0e20251ed309ca4fcce61c9d302214e789aa5e5839033db59744667fc35826cb98431c8ee684cfebb29a6e9117b8dc119825a7b0a24516

test:
  secret_key_base: 0ac74567e723372560cbcd300c06ee34f41d2108f33228e6d6e80f6f6072a8c980a53014526d11f9f6f190062bfe892bb820e9627b34a4660efe9c71475813f5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
